name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        cache: false
    - name: Build project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cargo build --release
    - name: Archive binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v1
      with:
        name: Linux
        path: target/release/licensor
    - name: Archive binary (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: Windows
        path: target/release/licensor.exe
    - name: Archive binary (macOS)
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v1
      with:
        name: macOS
        path: target/release/licensor
