name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        cache: false
    - name: Restore build artifacts
      uses: actions/download-artifact@v1
      with:
        name: target
        path: target
      continue-on-error: true
    - name: Build project
      run: cargo build
    - name: Archive build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
    - name: Archive binary (Unix)
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: licensor
        path: target/licensor
    - name: Archive binary (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: licensor.exe
        path: target/licensor.exe
